- .env
- app.js
- package-lock.json
- package.json
- server.js
server.js 와 app.js 코드 분리
server.js 로 서버 구동시켜야합니다!
> REFACTOR : 리팩토링

- .env
- .prettierrc.js
- app.js
- controller/userController.js
- models/user.js
- package-lock.json
- package.json
- router/userRouter.js
로그인과 회원가입 수정사항 추가,
CORS: add Front Serve,
DB 경로 수정
> 로그인, 회원가입, CORS, DB 수정

- .gitignore
- config/senderInfo.json
- controller/userController.js
- models/mail.js
- package-lock.json
- package.json
- router/userRouter.js
사용자가 회원가입 시 입력한 이메일로 인증번호 발급하는 기능 추가
> 사용자 메일 인증번호 발급 추가

- controller/userController.js
- models/user.js
> 회원가입 수정 및 이미지 추가

- models/user.js
> user 스키마 수정

- controller/userController.js
- middlewares/auth-middleware.js
> 인증미들웨어 및 로그인 수정

- app.js
- router/index.js
router를 묶는 index.js를 추가했고,
연결하기 위해서 app.js가 수정되었습니다.
> REFACTOR : 코드 리팩토링

- controller/userController.js
- router/userRouter.js
> sms코드 주석처리(임시)

- controller/userController.js
- models/user.js
- router/userRouter.js
email로 가입하던 걸 customerId를 넣고 이메일 인증을 통한 회원가입 수정 및 같은 방식으로 로그인 방식 변경, 이에 기반하여 전반적인 수정이 들어감
> 전반적인 user 수정

- config/SMSservice.json
- config/socialConfig.json
- controller/userController.js
- passport/google.js
- passport/kakao.js
> login 관련 일반/소셜 수정

- controller/roomController.js
- router/roomRouter.js
> jinhui/ 방나가기 기능 구현 및 추가

- controller/roomController.js
> 방나가기 에러 처리 추가

- controller/roomController.js
- controller/storeController.js
- router/storeRouter.js
feat : 맛집 지도 조회 API 구현 - 모든 맛집이 보여짐. 지도 반경 내로 filter 방법 찾기.
fix : 맛방 만들기 API fix - 사용자 자신은 멤버로 초대 불가.
> feat : 맛집 지도 조회 API 구현

- controller/storeController.js
지도 보여주기 API response에 storeId 를 추가하였습니다.
> fix : 지도 API response 수정

- router/roomRouter.js
> 사용자찾기 method change

- controller/roomController.js
> status값 수정

- controller/roomController.js
> 사용자 강퇴 버그 픽스

- controller/roomController.js
- models/store.js
> 맛방 리스트 조회 시 위도 경도 추가

- controller/userController.js
- router/userRouter.js
> 중복확인 API 분리

- controller/roomController.js
- controller/userController.js
> validation 수정 및 return 수정

- controller/roomController.js
- controller/userController.js
> validation errorMessage 처리 추가

- controller/socialController.js
> redirect URL 수정

- controller/userController.js
- router/userRouter.js
> 인증번호 메일 보내기 API 추가

- controller/userController.js
> 회원정보 가져오기 버그 수정

- controller/socialController.js
- controller/userController.js
> social login bug fix

- controller/roomController.js
- router/roomRouter.js
> 룸코드 찾기 API 구현

- controller/roomController.js
제한 조건 추가 : 
- 방 인원 20명 제한
- 방장이 자신 스스로를 멤버로 초대 불가
- 방이름 미기입 불가
> FIX : 방만들기 API 버그 픽스

- controller/socialController.js
> 소셜 RedirectUrl 변경

- controller/socialController.js
> 소셜redirectURL 변경

- controller/userController.js
> 이메일 찾기 메일 보내기 수정

- models/connect.js
- package-lock.json
- package.json
- server.js
- socket.js
> add/ socket

- controller/roomController.js
> 맛방전체조회 필요없는 코드 제거 및 리팩토링

- controller/analyzeCotroller.js
> fixed/ response값 수정

- controller/analyzeCotroller.js
> fixed/ res값 수정
